version: '3.8'

services:
  mongodb:
    build:
      context: ./database       # Votre dossier contenant le Dockerfile MongoDB
      dockerfile: Dockerfile    # Nom du fichier Dockerfile (vérifiez la casse)
    container_name: mongodb
    ports:
      - "27017:27017"          # Port exposé (host:container)
    volumes:
      - mongodb_data:/data/db   # Persistance des données
    networks:
      - app-network             # Réseau dédié
    restart: unless-stopped     # Redémarrage automatique sauf si stoppé manuellement

  contact-backend:
    image: contact-keeper-backend:latest
    container_name: contact-backend
    ports:
      - "5003:5000"            # Expose le port 5000 du container sur 5003 de l'hôte
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/contactkeeper  # Utilise le nom du service
    depends_on:
      - mongodb                # Attend que MongoDB soit démarré
    networks:
      - app-network
    restart: unless-stopped

  contact-frontend:
    image: contact-keeper-frontend:latest
    container_name: contact-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://contact-backend:5000  # Communication via le nom du service
    depends_on:
      - contact-backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:                 # Volume persistant pour MongoDB

networks:
  app-network:                  # Réseau personnalisé
    driver: bridge