version: '3.8'

services:
  mongodb:
    build:
      context: ./database       
      dockerfile: Dockerfile   
    container_name: mongodb
    ports:
      - "27017:27017"         
    volumes:
      - mongodb_data:/data/db   
    networks:
      - app-network           
    restart: unless-stopped     

  contact-backend:
    image: contact-keeper-backend:latest
    container_name: contact-backend
    ports:
      - "5003:5000"           
    environment:
      - PORT=5000# Utilise le nom du service
    depends_on:
      - mongodb              
    networks:
      - app-network
    restart: unless-stopped

  contact-frontend:
    image: contact-keeper-frontend:latest
    container_name: contact-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://contact-backend:5003  
    depends_on:
      - contact-backend
    networks:
      - app-network
    restart: unless-stopped
    

volumes:
  mongodb_data:                 

networks:
  app-network:                 
    driver: bridge