version: "3.8"
services:
  mongo:
    image: mongo:5
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/contactkeeper
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
