services:
  mongodb:
    build:
      context: ./database      
      dockerfile: Dockerfile  
    container_name: mongodb
    ports:
      - "27017:27017"        
    volumes:
      - mongodb_data:/data/db  
    networks:
      - app-network          
    restart: unless-stopped    

  contact-backend:
    image: contact-keeper-backend:latest
    container_name: contact-backend
    ports:
      - "5003:5000"          
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/mydatabase?authSource=admin   # Ajout de l'URI MongoDB
    depends_on:
      - mongodb              
    networks:
      - app-network
    restart: unless-stopped

  contact-frontend:
    build:
      context: .  # Contexte à la racine du projet
      dockerfile: nginx/Dockerfile.nginx
    container_name: contact-frontend
    ports:
      - "80:80"
    depends_on:
      - contact-backend
    networks:
      - app-network
    restart: unless-stopped
   
volumes:
  mongodb_data:                

networks:
  app-network:                
    driver: bridge