# Utiliser l'image officielle de Node.js
FROM node:18

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers nécessaires
COPY package*.json ./

# Installer les dépendances backend
RUN npm install

# Copier tout le reste du projet
COPY . .

# Exposer le port backend
EXPOSE 5000

# Démarrer le serveur Node.js
CMD ["npm", "start"]
