services:
  mongodb:
  
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  contact-backend:   
    image: contact-keeper-backend:latest
    container_name: contact-backend
    ports:
      - "5003:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/contactkeeper
    depends_on:
      - mongodb

  contact-frontend:
    image: contact-keeper-frontend:latest
    container_name: contact-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5003
    depends_on:
      - contact-backend

volumes:
  mongodb_data:
