# Utiliser l'image Nginx officielle
FROM nginx:alpine

# Copier la configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copier le build du frontend
COPY build/ /usr/share/nginx/html

# Exposer le port
EXPOSE 80
