# Utiliser une image officielle Node.js pour construire l'application
FROM node:18

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source du projet
COPY . .

ENV NODE_OPTIONS=--openssl-legacy-provider


# Construire l'application React pour la production
RUN npm run build

# Exposer le port utilisé par le serveur de développement React
EXPOSE 3000

# Démarrer l'application React
CMD ["npm", "start"]
